### ISSUE TITLE
Bug: addEventListener 중복되는 문제

### ISSUE THREAD

**Issue by gerry-mandering** [trancendering/frontend#13]
### Issue Type

- [x] Bug (오류)
- [ ] Feature Request (기능 요청)
- [ ] Performance (성능 문제)
- [ ] UI/Design (UI/디자인 관련)
- [ ] Documentation (문서 관련)
- [ ] Enhancement (개선 제안)
- [ ] Other - Please Describe:

### Priority

- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Summary
- 게임 연속 진행시 addEventListener 중복되는 문제

### Steps to Reproduce

1. 게임 연속 진행시 handleEvent() 가 중복으로 계속 등록됨
2. updatePaddleEvent 가 중복해서 트리거 됨
3.

### Environment

- Operating System:
- Browser (if applicable):
- Version:

### Additional Context

```
	async handleEvent() {
		document.addEventListener("keydown", (e) => {
			if (store.state.gameStatus !== "playing") return;
			if (store.state.gameContext.participated === false) return;
			if (e.key == "ArrowUp") {
				store.dispatch("moveUserPaddleUp");
			} else if (e.key == "ArrowDown") {
				store.dispatch("moveUserPaddleDown");
			}
		});
	}
```

**Comment by hey-uu** [comment]
handler 등록을 생성자에서 하도록 수정해서 문제 해결함
