### ISSUE TITLE
Bug: WebGL: INVALID_OPERATION 오류

### ISSUE THREAD

**Issue by hey-uu** [trancendering/frontend#15]
### Issue Type

- [x] Bug (오류)
- [ ] Feature Request (기능 요청)
- [ ] Performance (성능 문제)
- [ ] UI/Design (UI/디자인 관련)
- [ ] Documentation (문서 관련)
- [ ] Enhancement (개선 제안)
- [ ] Other - Please Describe:

### Priority

- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Steps to Reproduce

1. tournament 게임을 한 후 single 게임을 한다.
2. 아래와 같은 에러가 발생한다.

### Environment

- Operating System:
- Browser (if applicable):
- Version:

### Additional Context

에러 문구:
WebGL: INVALID_OPERATION: uniformMatrix3fv: location is not from current program
![Screenshot 2024-02-01 155535](https://github.com/trancendering/frontend/assets/89961266/eee8c6fb-8aad-49c5-ac0d-8e23339b2c14)

**Comment by gerry-mandering** [comment]
Issue resolved by integrating game.js and tournament.js
