### ISSUE TITLE
socket.io 주석 처리 이슈

### ISSUE THREAD

**Issue by tg201005** [trancendering/frontend#4]
### Issue Type

- [ ] Bug (오류)
### Priority

- [ ] Critical

### Summary

/static/store/socketHandler.js에서 socket.io 주석 처리가 안된 부분이 잇습니다. 
nginx에서 돌릴 때 이 부분으로 인해 컴파일 에러가 발생합니당. 이 부분 주석처리해주시면 감사하겠습니다!

### Steps to Reproduce

1.
2.
3.

### Environment

- Operating System:
- Browser (if applicable):
- Version:

**Comment by hey-uu** [comment]
socketHandler.js 파일이 삭제되어서 이제는 해당 오류가 나타나지 않을 것 같네요. 혹시 모르니 확인 부탁드립니다.
